import requests
import json
import io

# PlantNet API Configuration
# Get your FREE API key at https://my.plantnet.org/
PLANTNET_API_KEY = "2b104JJ5nvh0lhk2imBspR892O" 
PLANTNET_API_URL = f"https://my-api.plantnet.org/v2/identify/all?api-key={PLANTNET_API_KEY}"

def get_external_prediction(image_bytes: bytes) -> dict:
    """
    Calls the PlantNet API to identify plant species and potential diseases.
    """
    try:
        # Prepare the multipart form data
        files = [
            ('images', ('image.jpg', io.BytesIO(image_bytes), 'image/jpeg'))
        ]
        # Use common plant organs for better identification
        data = {'organs': ['leaf', 'flower', 'fruit', 'bark']}
        
        # Send the request
        response = requests.post(PLANTNET_API_URL, files=files, data=data)
        
        if response.status_code != 200:
            return {
                "success": False, 
                "error": f"External API Error: {response.status_code}",
                "detail": response.text
            }
        
        result = response.json()
        
        # Extract the best result
        if not result.get("results"):
            return {"success": False, "error": "No results found from External API."}
        
        best_match = result["results"][0]
        species_info = best_match.get("species", {})
        scientific_name = species_info.get("scientificNameWithoutAuthor", "Unknown")
        common_names = species_info.get("commonNames", [])
        display_name = common_names[0] if common_names else scientific_name
        
        # Determine if it's a disease based on common keywords
        # PlantNet results for disease often include diagnostic names in common names
        disease_keywords = ['rust', 'mildew', 'blight', 'spot', 'rot', 'mottle', 'virus', 'mold', 'scab', 'canker']
        found_disease = any(kw in display_name.lower() or any(kw in cn.lower() for cn in common_names) for kw in disease_keywords)
        
        is_healthy = not found_disease
        confidence = float(best_match.get("score", 0) * 100)
        
        if found_disease:
            rec_text = f"The external API detected signs of {display_name}. We recommend isolating the plant and applying a suitable fungicide or treatment."
            medicine_text = "Refer to professional agricultural guidance for this specific condition."
        else:
            rec_text = f"The external API identified this as {display_name}. No obvious disease was detected in the fallback analysis."
            medicine_text = "N/A"

        return {
            "success": True,
            "is_healthy": is_healthy,
            "disease_name": f"{display_name} (External API)",
            "confidence": confidence,
            "recommendation": rec_text,
            "medicine": medicine_text,
            "precaution": "This result was generated by the fallback identification service.",
            "prediction_source": "External API (PlantNet)"
        }
        
    except Exception as e:
        return {"success": False, "error": f"Fallback API Exception: {str(e)}"}
